// Package highlight provides class-based chroma syntax highlighting
// shared by the document and diff renderers, with a single generated
// stylesheet that covers light and dark themes.
package highlight

import (
	"bytes"
	"html"
	"strings"
	"sync"

	"github.com/alecthomas/chroma/v2"
	chromahtml "github.com/alecthomas/chroma/v2/formatters/html"
	"github.com/alecthomas/chroma/v2/lexers"
	"github.com/alecthomas/chroma/v2/styles"
)

const (
	lightStyle = "github"
	darkStyle  = "github-dark"
)

// LexerForLang returns a lexer by markdown fence language, falling back
// to content analysis and finally plain text.
func LexerForLang(lang, code string) chroma.Lexer {
	lexer := lexers.Get(lang)
	if lexer == nil && code != "" {
		lexer = lexers.Analyse(code)
	}
	if lexer == nil {
		lexer = lexers.Fallback
	}
	return chroma.Coalesce(lexer)
}

// LexerForFile returns a lexer by file name, falling back to plain text.
func LexerForFile(filename string) chroma.Lexer {
	lexer := lexers.Match(filename)
	if lexer == nil {
		lexer = lexers.Fallback
	}
	return chroma.Coalesce(lexer)
}

// Formatter is the shared class-emitting HTML formatter for whole code
// blocks (used by the markdown renderer).
var Formatter = chromahtml.New(
	chromahtml.WithClasses(true),
	chromahtml.PreventSurroundingPre(false),
)

// Style returns the light style; class-based output only uses it for CSS
// generation, but chroma's Format API still wants one.
func Style() *chroma.Style {
	if s := styles.Get(lightStyle); s != nil {
		return s
	}
	return styles.Fallback
}

var (
	sheetOnce sync.Once
	sheet     []byte
)

// Stylesheet returns CSS for the chroma classes: light rules at top
// level, dark rules scoped to the OS preference (unless the page forces
// light) and to an explicit data-theme="dark" override. Relies on CSS
// nesting, which every current browser supports.
func Stylesheet() []byte {
	sheetOnce.Do(func() {
		light := styleCSS(lightStyle)
		dark := styleCSS(darkStyle)
		var b bytes.Buffer
		b.WriteString("/* generated by chroma: " + lightStyle + " + " + darkStyle + " */\n")
		b.Write(light)
		b.WriteString("\n@media (prefers-color-scheme: dark) {\n  html:not([data-theme=\"light\"]) {\n")
		b.Write(dark)
		b.WriteString("  }\n}\nhtml[data-theme=\"dark\"] {\n")
		b.Write(dark)
		b.WriteString("}\n")
		sheet = b.Bytes()
	})
	return sheet
}

func styleCSS(name string) []byte {
	style := styles.Get(name)
	if style == nil {
		style = styles.Fallback
	}
	var b bytes.Buffer
	_ = Formatter.WriteCSS(&b, style)
	return b.Bytes()
}

// Range is a rune-offset interval [Start, End) to emphasize within a
// line, used for word-level diff highlighting.
type Range struct {
	Start, End int
}

// LineHTML tokenizes one source line and renders it with chroma classes,
// wrapping the rune ranges in emph with <span class="wd"> (word-diff
// emphasis). Falls back to escaped plain text if tokenizing fails.
func LineHTML(lexer chroma.Lexer, line string, emph []Range) string {
	it, err := lexer.Tokenise(nil, line)
	if err != nil {
		return html.EscapeString(line)
	}
	mask := emphMask(line, emph)
	var sb strings.Builder
	off := 0
	for _, tok := range it.Tokens() {
		val := tok.Value
		if val == "" {
			continue
		}
		cls := classFor(tok.Type)
		if cls != "" {
			sb.WriteString(`<span class="` + cls + `">`)
		}
		writeRuns(&sb, val, mask, &off)
		if cls != "" {
			sb.WriteString("</span>")
		}
	}
	return sb.String()
}

// writeRuns emits val, wrapping maximal runs of emphasized runes in a
// wd span. off tracks the rune offset into the whole line.
func writeRuns(sb *strings.Builder, val string, mask []bool, off *int) {
	runes := []rune(val)
	i := 0
	for i < len(runes) {
		em := masked(mask, *off+i)
		j := i
		for j < len(runes) && masked(mask, *off+j) == em {
			j++
		}
		seg := html.EscapeString(string(runes[i:j]))
		if em {
			sb.WriteString(`<span class="wd">` + seg + `</span>`)
		} else {
			sb.WriteString(seg)
		}
		i = j
	}
	*off += len(runes)
}

func masked(mask []bool, i int) bool {
	return i < len(mask) && mask[i]
}

func emphMask(line string, emph []Range) []bool {
	if len(emph) == 0 {
		return nil
	}
	n := len([]rune(line))
	mask := make([]bool, n)
	for _, r := range emph {
		for i := r.Start; i < r.End && i < n; i++ {
			if i >= 0 {
				mask[i] = true
			}
		}
	}
	return mask
}

func classFor(t chroma.TokenType) string {
	for t != 0 {
		if cls, ok := chroma.StandardTypes[t]; ok {
			return cls
		}
		t = t.Parent()
	}
	return chroma.StandardTypes[0]
}
